#!/bin/bash
## -/dat/usync/update ::

[[ $0 != "${BASH_SOURCE[0]}" ]] && return 0
print_help() { cat <<'HELPDOC'
Usage:
  update

Copy files to current directory.

Options:
  -H, --help    print help and exit

Environment:
  NO_COLOR      disable colored output

Files:
HELPDOC
local i=0
if ((${#files[@]}%2)); then
    printf '  error: files array contains odd number of files\n'
else
    while [[ $i -lt ${#files[@]} ]]; do
        printf "  ${files[i]} -> ${files[((i+1))]}\n"
        i=$((i+2))
    done
fi
exit "${1:-0}" ;}

## settings ::
debug=0 nocolor=0 quiet=0 verbose=0
files=()

## internal functions/variables ::
i=0
dir="$(realpath "${BASH_SOURCE%/*}")"

# colors, control sequences:
readonly clear_line=$'\e[2K'
black=$'\e[38;5;0m' blue=$'\e[38;5;12m' cyan=$'\e[38;5;14m' green=$'\e[38;5;10m'
grey=$'\e[38;5;8m' magenta=$'\e[38;5;13m' orange=$'\e[38;5;3m' red=$'\e[38;5;9m'
white=$'\e[38;5;15m' yellow=$'\e[38;5;11m' bold=$'\e[1m' off=$'\e[0m'
clear_colors() {
    export NO_COLOR=1 nocolor=1
    unset black blue cyan green grey magenta orange red white yellow bold off
}

# messages:
bin_printf() { printf "$@" ;}
[[ -f /usr/bin/printf ]] && bin_printf() { /usr/bin/printf "$@" ;}
msg() { printf "$bold$blue=> $off$white%s$off\n" "$*" ;}
msg2() { printf "$bold$blue > $off$white%s$off\n" "$*" ;}
msg2_warn() { printf "$bold${yellow} > $off$white%s$off\n" "$*" >&2 ;}
msg_error() { printf "$bold${red}E: $off$white%s$off\n" "$*" >&2 ;}
msg_good() { printf "$bold$green=> $off$white%s$off\n" "$*" ;}
msg_plain() { printf "$off$white   %s$off\n" "$*" ;}
msg_warn() { printf "$bold${yellow}W: $off$white%s$off\n" "$*" >&2 ;}
msg_cmd() { [[ $EUID -eq 0 ]] && printf "$bold$red:#" || printf "$bold$blue:$"
    printf "$off$white"; bin_printf ' %q' "$@"; printf "$off\n" ;}

# error, exit, trap:
error() { msg_error "$*"; exit 3 ;}
trap_exit() { ((debug)) && msg_warn '[exit]' ;}
trap_int() { printf '\n'; ((debug)) && msg_warn '[sigint]'; exit 99 ;}

## main ::
[[ $1 =~ ^(-H|--help)$ ]] && print_help
trap trap_int INT
trap trap_exit EXIT

# set from env:
[[ -n $DEBUG ]] && debug=1
[[ -n $NO_COLOR || ! -t 1 || ! -t 2 ]] && clear_colors
[[ -n $QUIET ]] && quiet=1 verbose=0
[[ -n $VERBOSE ]] && quiet=0 verbose=1

# errors:
[[ -z "$UDIR" ]] && error 'UDIR not set'
[[ ! -d "$UDIR" ]] && error "not a directory: $UDIR"
((${#files[@]}%2)) && error 'files array contains odd number of files'

# copy files:
while [[ $i -lt ${#files[@]} ]]; do
    if [[ -f "${files[i]}" ]]; then
        msg "${files[i]} $blue$bold->$white$off ${files[((i+1))]}"
        cp "${files[i]}" "${files[((i+1))]}"
    else
        msg_warn "not found: ${files[i]}"
    fi
    i=$((i+2))
done

# vim:ft=bash
